#!/bin/bash
# 0917 nav4 family on the decode-fix base (copy tree wsi_latent_0915_decode_hj).
#   ARM=base   : nav4 + decode fix, no C1            <- the new baseline for the nav4 board
#   ARM=eovc   : + --variant pruning_b + VLMAS_EOVC=1 (C2 #14 unexplained-variation coverage)
#   ARM=pruneb : + --variant pruning_b                (novelty + 0.25*texture + quota; §12 baseline)
#   ARM=secld  : + --variant pruning_b + VLMAS_SECLD=1 (C1 #19 spatial evidence-coverage log-det)
#   ARM=nova   : --variant base + VLMAS_C1_QASC=1 VLMAS_C1_SELECT=nova KEEP=0.25 (C1 #21 NOVA, post-vision, + C1META bridge)
#   ARM=nova_v2: nova + VLMAS_NOVA_V2=1 (Notion 09-17 15:13 v2: OD two-state EM posterior w_i + in-crop heat kernel d_grid=1)
# NOVA v2 copy (09-17 15:4x): generated by tmp_hj/make_nova_v2_launcher.py from rtask_nav4_nova_arm.sh, which is untouched.
#   ROOT runs/nav4_v2, own claim dir, hooks tmp_hj/nova_v2_hooks (chains lpvh_ntrs_hooks, then patches secld_select.evidence).
# (copy of rtask_nav4_secld_arm.sh with the nova arm and MAXUSED; same ROOT runs/nav4 and claim dir.)
# (copy of rtask_nav4_arm.sh with the secld arm; same ROOT runs/nav4 and claim dir.)
#
# nav4 is pinned: vision_text_mas/onepass_navigation_nav4.py md5 4f6e14a4 and
# vision_text_mas/onepass_navigator.py md5 198bf899, copied from wsi_latent_0902_2155_hj on 09-17.
# The navigator checks VLMAS_NAV4 BEFORE the nav3/nav2 branches, so nav4 wins; VLMAS_NAV2=1 is kept
# only because the Planner uses it to decode plan targets, and CROSS_SCALE_ROUTER stays 0.
# The PANDA x5 clamp patches onepass_navigation_roots, which nav4 also uses, so it still applies
# (the flag is named VLMAS_NAV3_X5_CLAMP for historical reasons).
# Decode fix is this tree's default; PANDA also gets VLMAS_ANSWERER_GRADE_RULE=1.
# usage: rtask_nav4_arm.sh <arm> <shard|smoke> <nshard> "<gpus>" [ds:n ...]
#   env OUTROOT / CLAIMDIR override the output root and the GPU claim dir.
set -u
ARM=${1:?arm}; SHARD=${2:?shard}; NSHARD=${3:?nshard}; GPUS=${4:?gpus}; shift 4
SPECS=${*:-tcga_expert_vqa:128 tcga_slidebench:197 gtex:190 tcga:221 panda:196}
MAXUSED=${MAXUSED:-2000}   # a GPU counts as free below this used-MiB (co-locate with one other run at 20000)
REPO=/home/users/whddn12316/wsi_latent_0915_decode_hj
DATA=/home/users/whddn12316/datasets/MultiPathQA/ready_wsivqa/full_no_panda
MODEL=/home/users/whddn12316/models/Qwen3-VL-4B-Thinking
PY=/home/users/whddn12316/venvs/wsi-latentmas-py312/bin/python
HOOKS=$REPO/tmp_hj/nova_v2_hooks
ROOT=${OUTROOT:-$REPO/sender_relay_exp/runs/nav4_v2}
VARIANT=base
case $ARM in
  base)   K=$ROOT/base;   ARMENV="" ;;
  eovc)   K=$ROOT/eovc;   VARIANT=pruning_b; ARMENV="VLMAS_EOVC=1" ;;
  pruneb) K=$ROOT/pruneb; VARIANT=pruning_b; ARMENV="" ;;
  secld)  K=$ROOT/secld;  VARIANT=pruning_b; ARMENV="VLMAS_SECLD=1" ;;
  nova)   K=$ROOT/nova;   ARMENV="VLMAS_C1_QASC=1 VLMAS_C1_SELECT=nova VLMAS_NOVA_KEEP=0.25 VLMAS_C1_META_BRIDGE=1" ;;
  nova_v2) K=$ROOT/nova_v2; ARMENV="VLMAS_C1_QASC=1 VLMAS_C1_SELECT=nova VLMAS_NOVA_KEEP=0.25 VLMAS_C1_META_BRIDGE=1 VLMAS_NOVA_V2=1" ;;
  *) echo "bad arm $ARM"; exit 2 ;;
esac
CLAIM=${CLAIMDIR:-$ROOT/claims}
LOG=$K/chain_${ARM}_shard$SHARD.log
RTASK=$'For each patch, examine its image quality, architecture, cellularity, cytology, stroma, necrosis, tissue boundary, artifacts, and relevance to the question. Focus only on visually observable findings and distinguish true tissue features from artifacts. State your best morphological read for every feature even when uncertain; do not report a feature as unresolvable.\n\nFormat your response as follows:\n- One bullet point per patch, starting with its patch ID, using terse 2-4 word phrases per feature.\n- Consistent findings: findings shared across patches and the patch IDs that support them.\n- Contradictions: disagreements between patches.\n- Unresolved evidence: what remains uncertain.\n- Diagnostically usable patches: patch IDs.\n\nDo not diagnose, choose an answer, or navigate.\nNow, output your response below:'
mkdir -p $K $CLAIM
log() { echo "$(date '+%m-%d %H:%M:%S') $*" >> $LOG; }
mem() { nvidia-smi --query-gpu=index,memory.used --format=csv,noheader,nounits | awk -F', *' -v g=$1 '$1==g{print $2}'; }

if [ "$SHARD" != smoke ]; then
  log "WAIT smoke gate"
  while [ ! -f $K/SMOKE_GATE_$ARM ]; do sleep 30; done
  grep -q ^PASS $K/SMOKE_GATE_$ARM || { log "SMOKE FAILED -> stop"; exit 1; }
fi

G=""
log "WAIT one of gpus [$GPUS] shard $SHARD/$NSHARD maxused=$MAXUSED"
while [ -z "$G" ]; do
  for g in $GPUS; do
    u=$(mem $g)
    if [ -n "$u" ] && [ "$u" -lt "$MAXUSED" ] && mkdir $CLAIM/claim_gpu$g 2>/dev/null; then G=$g; break; fi
  done
  [ -z "$G" ] && sleep 60
done
trap 'rmdir $CLAIM/claim_gpu$G 2>/dev/null' EXIT
log "CLAIM gpu$G shard=$SHARD arm=$ARM variant=$VARIANT nav4_md5=$(md5sum $REPO/vision_text_mas/onepass_navigation_nav4.py | cut -c1-8) navigator_md5=$(md5sum $REPO/vision_text_mas/onepass_navigator.py | cut -c1-8) backbone_md5=$(md5sum $REPO/backbone/qwen3vl.py | cut -c1-8) eovc_md5=$(md5sum $REPO/memory/eovc.py | cut -c1-8) secld_md5=$(md5sum $REPO/memory/secld_select.py | cut -c1-8) nova_md5=$(md5sum $REPO/memory/nova_select.py | cut -c1-8) nova_v2_md5=$(md5sum $REPO/memory/nova_v2_select.py | cut -c1-8) hook_md5=$(md5sum $HOOKS/sitecustomize.py | cut -c1-8) qasc_md5=$(md5sum $REPO/memory/qasc_select.py | cut -c1-8) used=$(mem $G)"

run() {
  local tag=$1 dsjson=$2 dest=$3; shift 3
  local out=$dest/gpu${G}_attempt_$(date +%Y%m%d_%H%M%S)
  mkdir -p $dest
  log "START $tag pending=$(( $# / 2 )) -> ${out#$K/}"
  cd $REPO && env \
    CUDA_VISIBLE_DEVICES=$G PYTHONPATH=$HOOKS:$REPO PYTHONUNBUFFERED=1 $ARMENV \
    VLMAS_PROMPT_SET=prompt1 VLMAS_ATTN_IMPLEMENTATION=sdpa \
    VLMAS_NAV4=1 VLMAS_NAV2=1 VLMAS_CROSS_SCALE_ROUTER=0 \
    VLMAS_NAV3_X5_CLAMP=1 VLMAS_EFF_DUMP=1 VLMAS_ANSWERER_GRADE_RULE=1 \
    VLMAS_REASONER_TASK="$RTASK" \
    $PY -m wsi_latentmas.pipeline.latent_mas \
    --variant $VARIANT --backbone qwen3-vl --dataset "$dsjson" --slide-root "$DATA/slides" \
    --model "$MODEL" --output-root "$out" --device cuda:0 \
    --latent-steps 10 --patch-budget 12 --max-model-len 12288 --navigator-control-tokens 512 \
    --temperature 0.0 --top-p 1.0 --seed 42 --deterministic --answerer-greedy --no-answerer-thinking \
    --answerer-max-new-tokens 512 --answerer-rationale --answerer-protocol structured_json \
    --canonical-open-options --navigator-kv --io-pipeline --no-save-navigation-pngs --case-retries 0 \
    "$@" > "$out.log" 2>&1 < /dev/null
  local rc=$?
  log "DONE $ARM $tag rc=$rc results=$(find $out -name result.json | wc -l) nav4=$(grep -l 'independent of the x5 selection' $(find $out -name navigator_calls.json) 2>/dev/null | wc -l) clamp=$(grep -c 'NAV3-X5CLAMP' $out.log) eovc=$(grep -c '^\[EOVC\]' $out.log) secld=$(grep -c '^\[SECLD\]' $out.log) nova=$(grep -c '^\[NOVA\] kept' $out.log) nova2=$(grep -c '^\[NOVA2\] n=' $out.log) nova2_patched=$(grep -c '^\[NOVA2\] patched' $out.log) c1meta_ok=$(grep -c '^\[C1META\] keep .* used=True meta=ok' $out.log) empty_crops=$(grep -o 'empty_crops=[0-9]*' $out.log | grep -vc 'empty_crops=0') prunev4=$(grep -c 'PruneVision/v4' $out.log) empty=$(grep -c 'EMPTY terminal answer' $out.log) tb=$(grep -c Traceback $out.log) oom=$(grep -ci 'out of memory' $out.log) eff=$(find $out -name efficiency.json | wc -l)"
}

if [ "$SHARD" = smoke ]; then
  run smoke $REPO/sender_relay_exp/smoke/gtex2.json $K/smoke_$ARM --dataset-index 0 --dataset-index 1
  o=$(ls -d $K/smoke_$ARM/gpu*_attempt_* | grep -v log$ | tail -1)
  r=$(find $o -name result.json | wc -l)
  n4=$(grep -l 'independent of the x5 selection' $(find $o -name navigator_calls.json) 2>/dev/null | wc -l); t=$(grep -c Traceback $o.log)
  em=$(grep -c 'EMPTY terminal answer' $o.log)
  ev=$(grep -c '^\[EOVC\]' $o.log); v4=$(grep -c 'PruneVision/v4' $o.log); sl=$(grep -c '^\[SECLD\]' $o.log); nv=$(grep -c '^\[NOVA\] kept' $o.log); n2=$(grep -c '^\[NOVA2\] n=' $o.log); n2p=$(grep -c '^\[NOVA2\] patched' $o.log)
  need_nv=0; { [ "$ARM" = nova ] || [ "$ARM" = nova_v2 ]; } && need_nv=2
  need_n2=0; [ "$ARM" = nova_v2 ] && need_n2=2
  ok2=1; if [ "$need_n2" -gt 0 ]; then { [ "$n2" -eq 2 ] && [ "$n2p" -gt 0 ]; } || ok2=0; else [ "$n2" -eq 0 ] || ok2=0; fi
  need_ev=0; [ "$ARM" = eovc ] && need_ev=$v4
  need_sl=0; [ "$ARM" = secld ] && need_sl=$v4
  need_v4=0; { [ "$ARM" = eovc ] || [ "$ARM" = pruneb ] || [ "$ARM" = secld ]; } && need_v4=1
  okv4=1; [ "$need_v4" -eq 1 ] && { [ "$v4" -gt 0 ] || okv4=0; }
  if [ "$r" -eq 2 ] && [ "$n4" -gt 0 ] && [ "$t" -eq 0 ] && [ "$em" -eq 0 ] \
     && [ "$ev" -eq "$need_ev" ] && [ "$sl" -eq "$need_sl" ] && [ "$nv" -eq "$need_nv" ] && [ "$okv4" -eq 1 ] && [ "$ok2" -eq 1 ]; then
    echo "PASS results=$r nav4=$n4 prunev4=$v4 eovc=$ev secld=$sl nova=$nv nova2=$n2 nova2_patched=$n2p empty=$em tb=$t" > $K/SMOKE_GATE_$ARM
  else
    echo "FAIL results=$r nav4=$n4 prunev4=$v4 eovc=$ev secld=$sl nova=$nv need_nova=$need_nv nova2=$n2 nova2_patched=$n2p need_nova2=$need_n2 need_eovc=$need_ev need_secld=$need_sl need_prunev4=$need_v4 empty=$em tb=$t" > $K/SMOKE_GATE_$ARM
  fi
  log "SMOKE $(cat $K/SMOKE_GATE_$ARM)"; exit 0
fi

for spec in $SPECS; do
  ds=${spec%%:*}; n=${spec##*:}
  done_ids=$(find $K/$ds -name result.json 2>/dev/null -exec $PY -c \
    'import json,sys; [print(json.load(open(f))["dataset_index"]) for f in sys.argv[1:]]' {} + | sort -n -u)
  ids=()
  for ((i=0; i<n; i++)); do
    [ $((i % NSHARD)) -eq "$SHARD" ] || continue
    grep -qx "$i" <<< "$done_ids" || ids+=(--dataset-index "$i")
  done
  if [ ${#ids[@]} -eq 0 ]; then log "SKIP $ds shard $SHARD complete"; continue; fi
  run $ds $DATA/$ds.json $K/$ds "${ids[@]}"
done
log "ALL DONE shard $SHARD"
touch $K/SHARD${SHARD}_${ARM}_DONE
