"""Frozen WSI search-tool interface for the opt-in search Navigator.

The Navigator controller (onepass_navigation_search) is backend-agnostic: it
emits one text evidence query per phase and receives raw crops plus geometry.
V0 ships one deterministic backend, TissueSearchTool, which reuses the frozen
tissue ranking already used for replacement/fallback everywhere else and
ignores the query text. Query-aware backends (PLIP/CONCH/BEACON) implement the
same two methods and swap in without touching the Navigator.

Invariants (fixed by design, do not relax):
- Navigator -> tool: structured query only; tool -> Navigator: crops + geometry.
- The tool never sees the question, the choices, or the latent state.
- Scale is decided by the phase (search_coarse -> x5, search_fine -> x20),
  never generated by the model.
- Retrieval scores stay inside the tool result and are never forwarded to
  the Reasoner.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass

from PIL import Image

from vision_text_mas.geometry import (
    Box,
    Magnification,
    edge_anchored_grid,
    eligible_tissue_ids,
    zoom_grid,
)
from vision_text_mas.navigation_render import SlideLike, render_box, tissue_fractions
from vision_text_mas.onepass_navigation_roots import (
    EXACT_X5_SIDE,
    MINIMUM_TISSUE_FRACTION,
    RootGrid,
)


@dataclass(frozen=True, slots=True)
class WSIObservation:
    """One retrieved crop with the geometry needed for provenance."""

    crop_id: str
    image: Image.Image
    scale: int
    box: Box
    parent_crop_id: str | None
    root_id: int
    candidate_id: int
    tissue_fraction: float
    score: float | None


@dataclass(frozen=True, slots=True)
class NavigationResult:
    """Final evidence bank handed to the Reasoner in one batch."""

    coarse_query: str
    fine_query: str
    coarse_crops: tuple[WSIObservation, ...]
    fine_crops: tuple[WSIObservation, ...]

    @property
    def all_crops(self) -> tuple[WSIObservation, ...]:
        return (*self.coarse_crops, *self.fine_crops)


class WsiSearchTool(ABC):
    """Frozen retrieval backend queried by the Navigator controller.

    Implementations must be deterministic for a fixed slide and query so a
    repeated call with a larger top_k extends the earlier ranking instead of
    reshuffling it (the controller relies on this for budget backfill).
    """

    @abstractmethod
    def search_coarse(
        self,
        slide: SlideLike,
        *,
        query: str,
        top_k: int,
    ) -> tuple[WSIObservation, ...]:
        """Return up to top_k x5 crops ranked for the query."""

    @abstractmethod
    def search_fine(
        self,
        slide: SlideLike,
        *,
        parent: WSIObservation,
        query: str,
        top_k: int,
    ) -> tuple[WSIObservation, ...]:
        """Return up to top_k x20 crops inside one parent x5 crop."""


class TissueSearchTool(WsiSearchTool):
    """V0 backend: deterministic tissue-fraction ranking, query-agnostic.

    This is the existing frozen replacement heuristic exposed through the tool
    interface; the query text is accepted but unused. Only crops at or above
    MINIMUM_TISSUE_FRACTION are ever returned, which keeps every observation
    valid for PatchMetadata (tissue_fraction >= 0.10).
    """

    def __init__(self, *, root_grid: RootGrid, crop_side: int = 512) -> None:
        self._root_grid = root_grid
        self._crop_side = crop_side

    def search_coarse(
        self,
        slide: SlideLike,
        *,
        query: str,
        top_k: int,
    ) -> tuple[WSIObservation, ...]:
        _ = query
        grid = self._root_grid
        ranked_roots = sorted(
            grid.eligible_ids,
            key=lambda root_id: (-grid.fractions[root_id - 1], root_id),
        )
        observations: list[WSIObservation] = []
        used_boxes: set[Box] = set()
        for root_id in ranked_roots:
            if len(observations) >= top_k:
                break
            root = grid.boxes[root_id - 1]
            if root.width < EXACT_X5_SIDE or root.height < EXACT_X5_SIDE:
                box = root
                candidate_id = 1
                fraction = grid.fractions[root_id - 1]
                crop_id = f"S5-{root_id}-ROOT"
            else:
                child = self._best_x5_child(
                    slide,
                    root=root,
                    used_boxes=used_boxes,
                )
                if child is None:
                    continue
                box, candidate_id, fraction = child
                crop_id = f"S5-{root_id}-{candidate_id}"
            if box in used_boxes:
                continue
            used_boxes.add(box)
            observations.append(
                WSIObservation(
                    crop_id=crop_id,
                    image=render_box(slide, box, max_side=self._crop_side),
                    scale=int(Magnification.X5),
                    box=box,
                    parent_crop_id=None,
                    root_id=root_id,
                    candidate_id=candidate_id,
                    tissue_fraction=fraction,
                    score=fraction,
                )
            )
        return tuple(observations)

    def search_fine(
        self,
        slide: SlideLike,
        *,
        parent: WSIObservation,
        query: str,
        top_k: int,
    ) -> tuple[WSIObservation, ...]:
        _ = query
        boxes = zoom_grid(parent.box, Magnification.X20)
        fractions = tissue_fractions(slide, boxes)
        eligible = eligible_tissue_ids(
            fractions,
            minimum_fraction=MINIMUM_TISSUE_FRACTION,
        )
        ranked_cells = sorted(
            eligible,
            key=lambda cell_id: (-fractions[cell_id - 1], cell_id),
        )
        return tuple(
            WSIObservation(
                crop_id=f"S20-{parent.crop_id}-{cell_id}",
                image=render_box(
                    slide, boxes[cell_id - 1], max_side=self._crop_side
                ),
                scale=int(Magnification.X20),
                box=boxes[cell_id - 1],
                parent_crop_id=parent.crop_id,
                root_id=parent.root_id,
                candidate_id=cell_id,
                tissue_fraction=fractions[cell_id - 1],
                score=fractions[cell_id - 1],
            )
            for cell_id in ranked_cells[:top_k]
        )

    def _best_x5_child(
        self,
        slide: SlideLike,
        *,
        root: Box,
        used_boxes: set[Box],
    ) -> tuple[Box, int, float] | None:
        """Mirror the frozen x5 replacement ranking without artifact dumps."""
        try:
            boxes = edge_anchored_grid(root, side=EXACT_X5_SIDE, rows=4, cols=6)
        except ValueError:
            return None
        fractions = tissue_fractions(slide, boxes)
        eligible = eligible_tissue_ids(
            fractions,
            minimum_fraction=MINIMUM_TISSUE_FRACTION,
        )
        candidates = tuple(
            candidate_id
            for candidate_id in eligible
            if boxes[candidate_id - 1] not in used_boxes
        )
        if not candidates:
            return None
        chosen = min(
            candidates,
            key=lambda candidate_id: (-fractions[candidate_id - 1], candidate_id),
        )
        return boxes[chosen - 1], chosen, fractions[chosen - 1]


class PlipSearchTool(TissueSearchTool):
    """Query-aware backend: PLIP text-image similarity over tissue-safe crops.

    Tissue eligibility (>= 0.10) stays the candidate filter; the ranking within
    eligible candidates is PLIP cosine similarity to the Navigator's evidence
    query. 0717 lesson: PLIP is OOD for raw questions but works on descriptive
    phrases - which is exactly what the Navigator emits here. Deterministic:
    greedy argmax with (-score, candidate order) tie-breaks, so a larger top_k
    extends the same ranking.
    """

    _shared_model = None
    _shared_processor = None

    def __init__(self, *, root_grid: RootGrid, crop_side: int = 512) -> None:
        super().__init__(root_grid=root_grid, crop_side=crop_side)
        self._ensure_model()

    @classmethod
    def _ensure_model(cls) -> None:
        if cls._shared_model is not None:
            return
        import os

        import torch
        from transformers import CLIPModel, CLIPProcessor

        path = os.environ.get(
            "VLMAS_PLIP_PATH", "/home/users/whddn12316/models/plip"
        )
        cls._shared_processor = CLIPProcessor.from_pretrained(path)
        model = CLIPModel.from_pretrained(path)
        device = "cuda:0" if torch.cuda.is_available() else "cpu"
        cls._shared_model = model.to(device).eval()

    def _plip_rank(
        self,
        query: str,
        images: list[Image.Image],
    ) -> list[int]:
        """Return candidate offsets ranked by descending PLIP similarity."""
        return self.rank_images(query, images)

    @classmethod
    def rank_images(cls, query: str, images: list[Image.Image]) -> list[int]:
        """Class-level PLIP ranking (shared frozen model), usable without a tool
        instance -- e.g. the grid Navigator's x20 re-ranking hook."""
        import torch

        cls._ensure_model()
        model = cls._shared_model
        processor = cls._shared_processor
        assert model is not None and processor is not None
        device = next(model.parameters()).device

        def as_embedding(output: object) -> torch.Tensor:
            """get_*_features returns a tensor or a ModelOutput by version."""
            if isinstance(output, torch.Tensor):
                return output
            for attr in ("text_embeds", "image_embeds", "pooler_output"):
                value = getattr(output, attr, None)
                if isinstance(value, torch.Tensor):
                    return value
            raise TypeError(f"unexpected CLIP feature output: {type(output)}")

        with torch.no_grad():
            text_inputs = processor(
                text=[query], return_tensors="pt", padding=True, truncation=True, max_length=77
            ).to(device)
            text_emb = as_embedding(model.get_text_features(**text_inputs))
            text_emb = text_emb / text_emb.norm(dim=-1, keepdim=True)
            image_inputs = processor(images=images, return_tensors="pt").to(device)
            image_emb = as_embedding(model.get_image_features(**image_inputs))
            image_emb = image_emb / image_emb.norm(dim=-1, keepdim=True)
            scores = (image_emb @ text_emb.T).squeeze(-1).tolist()
        return sorted(range(len(images)), key=lambda i: (-scores[i], i))

    def search_coarse(
        self,
        slide: SlideLike,
        *,
        query: str,
        top_k: int,
    ) -> tuple[WSIObservation, ...]:
        # Candidate pool. With one child per root the query only decides WHICH
        # root to visit -- the position inside the root stays tissue-argmax.
        # VLMAS_NAV_PLIP_PER_ROOT>1 widens the pool to the N most tissue-safe
        # children of each root, so the query also picks the position within a
        # root. Default 1 keeps the earlier behaviour byte-identical.
        import os

        per_root = max(1, int(os.environ.get("VLMAS_NAV_PLIP_PER_ROOT", "1")))
        if os.environ.get("VLMAS_NAV_PLIP_COARSE", "1") == "0":
            # Diagnostic arm: x5 parents by the frozen tissue ranking (query
            # ignored), PLIP only inside the parents (search_fine). Isolates
            # how much of the PLIP effect comes from the x5 choice.
            return super().search_coarse(slide, query=query, top_k=top_k)
        if per_root == 1:
            pool = super().search_coarse(
                slide, query=query, top_k=len(self._root_grid.boxes))
        else:
            pool = self._wide_coarse_pool(slide, per_root=per_root)
        if not pool:
            return ()
        order = self._plip_rank(query, [obs.image for obs in pool])
        chosen: list[WSIObservation] = []
        used_boxes: set[Box] = set()
        for index in order:
            candidate = pool[index]
            if candidate.box in used_boxes:
                continue
            chosen.append(candidate)
            used_boxes.add(candidate.box)
            if len(chosen) >= top_k:
                break
        return tuple(chosen)

    def _wide_coarse_pool(
        self,
        slide: SlideLike,
        *,
        per_root: int,
    ) -> tuple[WSIObservation, ...]:
        """Up to per_root tissue-safe x5 children from every eligible root."""
        grid = self._root_grid
        pool: list[WSIObservation] = []
        for root_id in sorted(grid.eligible_ids):
            root = grid.boxes[root_id - 1]
            try:
                boxes = edge_anchored_grid(root, side=EXACT_X5_SIDE, rows=4, cols=6)
            except ValueError:
                continue
            fractions = tissue_fractions(slide, boxes)
            eligible = eligible_tissue_ids(
                fractions, minimum_fraction=MINIMUM_TISSUE_FRACTION
            )
            ranked = sorted(
                eligible, key=lambda cid: (-fractions[cid - 1], cid)
            )[:per_root]
            for candidate_id in ranked:
                box = boxes[candidate_id - 1]
                pool.append(
                    WSIObservation(
                        crop_id=f"S5-{root_id}-{candidate_id}",
                        image=render_box(slide, box, max_side=self._crop_side),
                        scale=int(Magnification.X5),
                        box=box,
                        parent_crop_id=None,
                        root_id=root_id,
                        candidate_id=candidate_id,
                        tissue_fraction=fractions[candidate_id - 1],
                        score=fractions[candidate_id - 1],
                    )
                )
        return tuple(pool)

    def search_fine(
        self,
        slide: SlideLike,
        *,
        parent: WSIObservation,
        query: str,
        top_k: int,
    ) -> tuple[WSIObservation, ...]:
        pool = super().search_fine(slide, parent=parent, query=query, top_k=16)
        if not pool:
            return ()
        order = self._plip_rank(query, [obs.image for obs in pool])
        return tuple(pool[i] for i in order[:top_k])


def build_search_tool(*, root_grid: RootGrid) -> WsiSearchTool:
    """Select the frozen backend by VLMAS_NAV_SEARCH_TOOL (default tissue)."""
    import os

    name = os.environ.get("VLMAS_NAV_SEARCH_TOOL", "tissue")
    if name == "tissue":
        return TissueSearchTool(root_grid=root_grid)
    if name == "plip":
        return PlipSearchTool(root_grid=root_grid)
    raise ValueError(f"unknown WSI search tool backend: {name!r}")
